language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.4.10 WP_MULTISITE=0
    - WP_VERSION=4.4.10 WP_MULTISITE=1
matrix:
    include:
       - php: 5.3
         env: WP_VERSION=latest WP_MULTISITE=0 TEST_GROUP=--group=uninstall
       - php: 5.3
         env: WP_VERSION=latest WP_MULTISITE=1 TEST_GROUP=--group=uninstall
       - php: 5.6
         env: WP_VERSION=latest WP_MULTISITE=0 TEST_GROUP=--group=uninstall
       - php: 5.6
         env: WP_VERSION=latest WP_MULTISITE=1 TEST_GROUP=--group=uninstall
before_script:
  - composer require --dev phpunit/phpunit:\<6.0
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: vendor/bin/phpunit $TEST_GROUP